### ISSUE TITLE
Sorry for bother u.. I have a question, can u help me..

### ISSUE THREAD

**Issue by Goddywu** [PAEz/QtTabBar-Scripts#1]
Because I cannot find how to contact u, I just find this weird way to ask my question.

I have seen u answer the question "https://stackoverflow.com/questions/11684454/getting-the-source-html-of-the-current-page-from-chrome-extension?answertab=votes#tab-top". It works well for me. 

I decide to use ["vue-web-extension"](https://github.com/Kocal/vue-web-extension) to build chrome extension. However, after several tries, I have no idea how to mix the above answer and vue-web-extension well. 

If u have any idea, please write solution in https://stackoverflow.com/questions/56964537/getting-the-source-html-of-the-current-page-from-vue-web-extension . Or here https://github.com/Kocal/vue-web-extension/issues/449

Thx anyway. （u can close this weird issue 😰）  @PAEz

**Comment by PAEz** [comment]
Hey ya closed it, did you get it?
Was just about to try for you.

**Comment by Goddywu** [comment]
@PAEz  Yep, I got a way to build it.  I am writing a blog to show how to do it...  

My English is poor, and trying to describe build such a chrome plugin project:
- use vue
- use element-ui and iview (vue ui tools)        (fix by author: https://github.com/Kocal/vue-web-extension/issues/444)
- get source html

give u a quick answer, here is my solution,
don't use route when u init the vue-web-extension project, and then ...
![image](https://user-images.githubusercontent.com/29056050/60955276-19061780-a333-11e9-9d6c-b13bcc0efb25.png)
![image](https://user-images.githubusercontent.com/29056050/60955409-5a96c280-a333-11e9-9c04-6dfceb053ba0.png)
![image](https://user-images.githubusercontent.com/29056050/60955326-2cb17e00-a333-11e9-9f99-fb62aed42c96.png)

It's seems working well now...    Thank you for caring about my question. 😂

**Comment by PAEz** [comment]
hehehe cool :P
Here's what I did, keeping in mind I DONT know vue at all....Im trying to learn Svelte
App.vue
```
<template>
  <div>
    <p>Hello world!</p>
    <button @click="test">Get Source</button>
    {{source}}
  </div>
</template>

<script>
export default {
  mounted: function() {
    let v=this;
    chrome.runtime.onMessage.addListener(function(request, sender) {
      if (request.action == 'getSource') {
        v.source=request.source;
      }
    });
  },
  data() {
    return {source:''};
  },
  methods: {
    test: function() {
      let v=this;
      chrome.tabs.executeScript(
        null,
        {
          file: 'getPagesSource.js',
        },
        function() {
          // If you try and inject into an extensions page or the webstore/NTP you'll get an error
          if (chrome.runtime.lastError) {
            v.source=chrome.runtime.lastError.message;
          }
        }
      );
    },
  },
};
</script>

<style lang="scss">
p {
  font-size: 20px;
}
body {
  min-width:500px;
  min-height:500px;
}
</style>
```
